# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# export User Defined Config path variable
export ZSH_CONFIG_PATH="$BASE_CONFIG_PATH/zsh_config"
export GIT_CONFIG_PATH="$BASE_CONFIG_PATH/git_config"
export VIM_CONFIG_PATH="$BASE_CONFIG_PATH/vim_config"

# zsh config
export LANG=en_US.UTF-8
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi
### End of Zinit's installer chunk

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"

autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# source $ZSH_CONFIG_PATH/pure/zsh_pure.zsh
zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

# plugin list
# 自动补全
zinit ice lucid wait='0'
zinit light zsh-users/zsh-completions
# 自动建议
zinit ice lucid wait="0" atload='_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions
# 高亮
zinit ice lucid wait='0' atinit='zpcompinit'
zinit light zdharma-continuum/fast-syntax-highlighting
# git alias
zinit ice lucid wait='1'
zinit snippet OMZ::plugins/git/git.plugin.zsh
# zoom
zinit ice wait'!0' 
zinit light skywind3000/z.lua
export _ZL_DATA=$XDG_CONFIG_HOME/zlua/.zlua
# history word
zinit ice lucid wait='0'
zinit light zdharma-continuum/history-search-multi-word
# # fzf
# zinit ice lucid wait='0'
# zinit light unixorn/fzf-zsh-plugin
# export FZF_PATH=${HOME}/.config/fzf
# export FZF_PREVIEW_ADVANCED=less
# export LESSOPEN="|/opt/homebrew/bin/lesspipe.sh %s"

# ignore case sensitive 
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
autoload -Uz compinit && compinit

# fuck
eval $(thefuck --alias)

# fzf
eval "$(fzf --zsh)"
export FZF_DEFAULT_OPTS='--preview "bat --style=numbers --color=always --line-range :500 {}"'

# bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# activate scripts 
source $ZSH_CONFIG_PATH/scripts/common.sh